knative/build

- README.md
Remove duplicate content (allow docs repo to provide those details) and highlight Knative build purpose. Also removed "getting started" task content (intend on moving to the knative/docs/build repo as a task topic - inprogress).
/assign @ImJasonH @christophersanson 
```release-note NONE
```
> Edit knative/build readme.md

- pkg/builder/common.go
- pkg/builder/common_test.go
- test/template-args/0-template.yaml
/cc @vbatts 
/assign mattmoor
```release-note
Template args are applied to build step images
```
> Apply template args to step image

- config/300-build.yaml
- config/300-buildtemplate.yaml
- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
- pkg/builder/cluster/builder.go
Add 'completed' column to 'get' cli to clearly indicate whether a build
has completed. Also add 'completed steps' field which can be used to
more easily determine current build status.
Fixes #233
```release-note 
Add completed column and stepsCompleted to CLI
```
> Show additional build state info in CLI

- pkg/builder/cluster/convert/convert.go
Fixes #295 
* Label build pods with `build.knative.dev/buildName` instead of un-namespaced `build-name`
* Log `Build successful` when build pod init containers are done, instead of the misleading and anachronistic `Nothing to push`
```release-note
Build pods labels are namespaced
```
> Minor quality of life improvements

- .gitignore
- Gopkg.lock
- Gopkg.toml
- pkg/builder/cluster/convert/convert.go
- pkg/builder/cluster/convert/convert_test.go
- pkg/builder/cluster/convert/testdata/workspace.yaml
- test/home-volume/test.yaml
- third_party/VENDOR-LICENSE
- vendor/github.com/sergi/go-diff/AUTHORS
- vendor/github.com/sergi/go-diff/CONTRIBUTORS
- vendor/github.com/sergi/go-diff/LICENSE
- vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
Redo of #229, my fork went weird after the repo opening :man_shrugging: 
Related to #52 
* Allow steps to specify `volumeMounts` with a `mountPath` that conflicts with the implicit volume mounts we typically attach (`/workspace` and `/builder/home`).
* If such a `volumeMount` is specified, the implicit volume mount is not attached.
* Add unit tests and integration tests
```release-note
NONE
```
> Allow steps to mount a volume over implicit volume mounts

- test/presubmit-tests.sh
1. make the presubmit.sh script more portable so it can be run on mac os 
2. similar to https://github.com/knative/build/pull/307 
```
"NONE"
```
> Also make presubmit-tests.sh portable

- pkg/builder/cluster/builder.go
- pkg/builder/cluster/builder_test.go
- test/multiple-steps/build-with-more-steps.yaml
Fixes #304 
* Intermediate build steps like `waiting`, `running`.
> Show intermediate update of build steps

- hack/verify-codegen.sh
OS X's `mktemp` has no `-p` flag.
> Make verify-codegen.sh compatible with OS X

- DEVELOPMENT.md
* add step in local development readme to cleanup `clusterbuildtemplates`
```
"NONE".
```
> add cleanup step for clusterbuildtemplates in doc

- images/Dockerfile
Related to https://github.com/knative/build/issues/179
* Add a Dockerfile to generate a minimal base image to be used by build
* Once this image is published, the `.ko.yaml` file should be updated to point to it
```
Base image used by build now based on alpine to make downloads faster
```
> Dockerfile for new minimal base image based on alpine

- .ko.yaml
- hack/release.sh
Fixes #179
* Build the common base image added in #317 during `hack/release.sh` (and build it once manually just now)
* Specify this base image in `.ko.yaml` so `git-init` and `creds-init` images are built atop it.
```release-note
NONE
```
/cc @pivotal-nader-ziada 
/assign mattmoor
> Build smaller base image in release.sh

- pkg/apis/build/v1alpha1/build_types.go
- pkg/builder/cluster/builder.go
- pkg/builder/cluster/builder_test.go
- pkg/builder/interface.go
- pkg/builder/nop/builder.go
- pkg/controller/build/controller.go
- pkg/controller/build/controller_test.go
- pkg/webhook/build.go
- pkg/webhook/webhook_test.go
- test/build-with-timeout/build-with-high-timeout.yaml
- test/build-with-timeout/build-with-low-timeout.yaml
Fixes #254 
* Introduce build timeout under `timeout`
* Default timeout is 10min.
> Add build timeout

- test/build-with-timeout/build-with-high-timeout.yaml
- test/build-with-timeout/build-with-low-timeout.yaml
- test/e2e/simple_test.go
> Test cleanup

- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
- pkg/builder/cluster/convert/convert.go
- test/e2e/e2e.go
- test/e2e/simple_test.go
Fixes #237 
* Operator can specify pod affinity for builds.
* e2e test timesout because of missing pod constraints.
> Add Pod affinity to builds

- test/e2e/simple_test.go
Otherwise we actually dereference a nil pointer in some cases.
> Make an Errorf be Fatalf instead.

- pkg/builder/cluster/builder.go
- pkg/builder/cluster/builder_test.go
- pkg/builder/cluster/convert/convert_test.go
- pkg/builder/interface.go
- pkg/builder/nop/builder.go
- pkg/builder/nop/builder_test.go
- pkg/buildtest/diff.go
- pkg/controller/build/controller.go
Fixes #338 
* If a build specifies no source, skip only the first `StepState`
* If the build specifies source, skip the first _two_ `StepState`s
* Add tests, and move `diffmatchpatch` helper to `pkg/buildtest`
```release-note
.Status.StepStates omits states for implicit steps, so the number of StepStates == number of user-specified build steps
```
/assign @shashwathi
> Trim StepStates for implicit steps

- Gopkg.lock
- cmd/controller/main.go
- config/200-clusterrole.yaml
- pkg/reconciler/buildtemplate/buildtemplate.go
- third_party/VENDOR-LICENSE
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/errgroup/errgroup.go
After this the two remaining pieces are:
1. Mirroring this logic into ClusterBuildTemplate (instantiating Images in `knative-build`)
1. Unit testing (once the facilities to do so exist).
WIP until https://github.com/knative/build/pull/352 is merged.
> Have the BuildTemplate controller instantiate Image resources.

- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
- pkg/builder/interface.go
- pkg/controller/build/controller.go
- pkg/controller/build/controller_test.go
- pkg/webhook/build.go
- pkg/webhook/webhook_test.go
- test/e2e/simple_test.go
Fixes #335 
* Follow up PR to update type from string to k8s Duration type
cc @tcnghia
> Use k8s Duration instead of string for build timeout

- cmd/nop/main.go
- config/999-cache.yaml
- config/controller.yaml
- pkg/builder/cluster/convert/convert.go
- pkg/builder/cluster/convert/convert_test.go
* Build a custom image with Go binary that prints `Build successful` and exits
* Specify this image to the controller by flag
* Use this image instead of `busybox` running `echo Build successful`
* Cache this image
```release-note
```
> Use custom nop image instead of busybox

- test/columns.txt
Prior to this, `kubectl get builds -o=custom-columns-file=test/columns.txt` would show output like:
```
NAME                              TYPE     STATUS    ...
test-build                        <none>   True      ... 
```
After this change, it's:
```
NAME                              TYPE        STATUS    ...
test-build                        Succeeded   True      ...
```
```release-note
NONE
```
> Fix columns.txt TYPE column

- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/build_types_test.go
Related to  knative/pkg#97
Those calls to `duck.VerifyType` are done at runtime and thus could be
costly at program startup. Putting them under tests ensure we still
assert those types but during unit testing.
> Move the use of `VerifyType` in tests

- hack/release.sh
- hack/update-codegen.sh
- hack/update-deps.sh
- hack/verify-codegen.sh
- test/e2e-tests.sh
Some systems may not have /bin/bash (NixOS for example)… Using
/usr/bin/env bash has the benefit of looking for whatever the
default version of the program is in your current environment.
Same as knative/pkg#107 
/assign @adrcunha
> Use `/usr/bin/env bash` instead of `/bin/bash`

- .ko.yaml
- hack/release.sh
Let's put all knative/build images together, it's cleaner.
Part of https://github.com/knative/test-infra/issues/161
Bonus: separate building and pushing the base images, so you can safely use `--nopublish`.
> Move build-base to the build dir in GCR

- pkg/builder/cluster/convert/convert_test.go
- pkg/webhook/build.go
- pkg/webhook/webhook_test.go
Fixes #397 
> PR https://github.com/knative/build/pull/204 renamed `*.build.dev` in `build.knative.dev`. Somehow there is still some code that refers to the old `build.dev` name, mainly for webook secret validate
> Migrate last pieces of build.dev to build.knative.dev

- test/columns.txt
Before:
```
NAME                   TYPE        STATUS    CREATED   START                  END
test-custom-env-vars   Succeeded   True      <none>    2018-10-01T16:34:55Z   2018-10-01T16:34:59Z
```
After:
```
NAME                   TYPE        STATUS    CREATED                START                  END
test-custom-env-vars   Succeeded   Unknown   2018-10-01T16:34:54Z   2018-10-01T16:34:55Z   2018-10-01T16:34:58Z
```
```release-note
NONE
```
> List metadata.creationTimestamp in columns.txt

- test/README.md
- test/e2e-common.sh
- test/e2e-yaml-tests.sh
- test/e2e/README.md
Taking from `serving` `test/README`(s), this updates the documentation
to run the unit tests and e2e tests locally.
/cc @shashwathi @ImJasonH 
> Update test documentation

- test/e2e/invalid_test.go
Fixes #396 
* Add a new test that sends expected-invalid builds and fails if they are accepted
Against a cluster from HEAD, the `negative-timeout` test fails, indicating that isn't being checked. 👎 
```release-note
NONE
```
/assign shashwathi
> Add e2e test for invalid builds

- test/e2e-tests.sh
- test/e2e/simple_test.go
* Optionally emit a metric that tracks how long a simple no-op build takes to schedule, execute and finish watching. This should help us identify serious latency regressions that might affect all builds.
I'm pretty sure there's more I need to do here, to get these metrics displayed at http://testgrid.knative.dev/knative-build -- like [knative/serving has](http://testgrid-dot-knative-tests.appspot.com/knative-serving#latency). I'm not sure if that change happens in this repo somehow/somewhere, or in whatever config powers testgrid. /cc @jessiezcc 
```release-note
NONE
```
/hold
> Emit metric to track null build latency

- .github/issue-template.md
- .github/pull-request-template.md
* Make it harder for users to accidentally add a rainbow of labels and assign a non-member user ([this poor sap](https://github.com/user)). Now users must explicitly remove the leading `>` to add a `kind` or `area` label or `assign` a user.
* Tell Prow to `/lint` PRs by default
```release-note
NONE
```
> Update issue and PR templates

- pkg/builder/common.go
- pkg/builder/common_test.go
This functionality will be used in build-pipeline as well, and reusing
this logic will help ensure consistency.
Should be used for https://github.com/knative/build-pipeline/issues/64
* Extract logic from ApplyTemplate into a new, public function `ApplyReplacements`
```release-note
NONE
```
/lint
> Extract the ApplyReplacements logic from ApplyTemplate.

- config/controller.yaml
- config/webhook.yaml
- pkg/system/names.go
In anticipation of #391, this removes the hard-coded namespace from the go source by using the downward API per @mattmoor 's example.
Removing the namespace from the yaml manifests is more complicated, as it will likely impact the install instructions and the test/release infrastructure.
> Use downward API instead of hard-coding build namespace

- WORKSPACE
- hack/release.sh
- images/BUILD
- images/Dockerfile
This makes Knative container images uniform for the sake of
license scanning
Bazel is introduced again so we can use rules provided by
github.com/GoogleContainerTools/distroless to build our base
container images
> Use gcr.io/distroless/base for the build-base image

- test/e2e-tests.sh
My current theory is the webhook is not registered/running when the tests start.
This waits until all pods in the knative-build namespace have their 'Ready' condition set to true.
> Fix e2e:TestInvalidBuild flakiness 

- test/e2e-common.sh
- test/e2e-tests.sh
- test/e2e-yaml-tests.sh
Since Openshift provides its own Build CRD, that name takes precedence
and causes the e2e test logic to fail.
Using the FQN should enable tests to pass on either k8s or openshift platforms.
> Use fully-qualified name to avoid conflict w/Openshift Builds

- hack/README.md
- hack/release.md
- hack/release.sh
`test-infra` is updated to the latest version to include the required infrastructure.
Bonuses:
* documented the contents of the `hack` directory;
* documented how to use the `release.sh` script;
> Automate the creation of versioned releases

- hack/README.md
- hack/release.md
- hack/release.sh
`test-infra` is updated to the latest version to include the required infrastructure.
Bonuses:
* documented the contents of the `hack` directory;
* documented how to use the `release.sh` script;
> [RELEASE-0.2] Pull in updates to release automation

- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
- pkg/builder/cluster/builder.go
- pkg/builder/nop/builder.go
- pkg/reconciler/build/build.go
- pkg/reconciler/build/build_test.go
This is recommended api convention by k8s.
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required
* Add `+optional` tags
> Add optional tags for build spec

- test/sources/test-gopath.yaml
This PR includes e2e test of using `targetPath` in a valid use-case i.e., source copied into targetpath and running go tests.
> Add e2e test for sources with targetpath

- test/e2e/simple_test.go
This test randomly fails on our OpenShift instance due to timeout. I think increasing the timeout to 120 is sufficient in general (it passes constantly in our case).
> Increase timeout for TestSimpleBuild

- pkg/builder/cluster/builder.go
- pkg/builder/cluster/builder_test.go
Fixes #474 
* Fixed swapped reason/message when pod is initializing.
```release-note
None
```
> Fix swapped reason/message when pod is initializing

- test/e2e/simple_test.go
> Follow up with more aggressive collapse.

- pkg/reconciler/build/build.go
- pkg/reconciler/build/build_test.go
In case a build has not been yet started (i.e. no Pod), we validate
the build spec and then we create and start the Pod for this build. In
case the validation fail, we return an error and never update the
build status, making it hard to know why it doesn't work.
Fixes #471 
> Populate status in case of validation errors 👷

- Gopkg.lock
- vendor/github.com/google/licenseclassifier/LICENSE
- vendor/github.com/google/licenseclassifier/classifier.go
- vendor/github.com/google/licenseclassifier/file_system_resources.go
- vendor/github.com/google/licenseclassifier/forbidden.go
- vendor/github.com/google/licenseclassifier/internal/sets/sets.go
- vendor/github.com/google/licenseclassifier/internal/sets/stringset.go
- vendor/github.com/google/licenseclassifier/license_type.go
- vendor/github.com/google/licenseclassifier/licenses/Unlicense.txt
- vendor/github.com/google/licenseclassifier/stringclassifier/LICENSE
- vendor/github.com/google/licenseclassifier/stringclassifier/classifier.go
- vendor/github.com/google/licenseclassifier/stringclassifier/internal/pq/priority.go
- vendor/github.com/google/licenseclassifier/stringclassifier/searchset/searchset.go
- vendor/github.com/google/licenseclassifier/stringclassifier/searchset/tokenizer/tokenizer.go
- vendor/github.com/knative/test-infra/tools/dep-collector/README.md
- vendor/github.com/knative/test-infra/tools/dep-collector/imports.go
- vendor/github.com/knative/test-infra/tools/dep-collector/licenses.go
- vendor/github.com/knative/test-infra/tools/dep-collector/main.go
Scripts that update deps needed to have `dep-collector` (and
`licenseclassifier` which it uses) vendored in order to be able to
automatically install when they are not present.
Having an older version of `dep-collector` resulted in the following
error when trying to update the vendored code:
```
`Error identifying licenses for transitive dependencies: unable to find license for "github.com/knative/build-pipeline/vendor/github.com/joho/godotenv"`
```
This is resolved in a newer version of `dep-collector`.
Unfortunately, if something like this happens again, folks will still
need to realize they have an older version of `dep-collector` and remove
it before running these scripts.
This was also fixed in build-pipeline in https://github.com/knative/build-pipeline/pull/290
```release-note
NONE …
```
> Fix scripts to install dep-collector when not present

- Gopkg.lock
- Gopkg.toml
We need it as a tool, but not its dependencies.
For details, see knative/build#487 (comment)
> Add dep-collector to the list of required tools in Gopkg.toml

- DEVELOPMENT.md
- README.md
- code-of-conduct.md
- hack/README.md
- hack/release.md
- roadmap-2018.md
- test/README.md
- test/e2e/README.md
Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
> Format markdown

- DEVELOPMENT.md
Fixes #
Found docs in `serving/development.md` regarding using docker hub with`KO_DOCKER_REPO` and amended the `build/development.md` docs with the information.
Using ```hub.docker/r/<username>/<repo-name>``` gives a 404 error when running `ko apply config/`
* Amend `DEVELOPMENT.md` with docker hub usage instructions with `ko` - specifically for `KO_DOCKER_REPO`
```release-note
NONE
```
> Amended docs for using docker hub with KO_DOCKER_REPO

- pkg/logs/logs.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
> golang format tools

- config/200-clusterrole.yaml
- config/300-build.yaml
- config/300-buildtemplate.yaml
- config/300-clusterbuildtemplate.yaml
- pkg/apis/build/v1alpha1/build_template_types.go
- pkg/apis/build/v1alpha1/build_template_types_test.go
- pkg/apis/build/v1alpha1/build_types.go
- pkg/apis/build/v1alpha1/build_types_test.go
- pkg/apis/build/v1alpha1/cluster_build_template_types_test.go
- pkg/client/clientset/versioned/typed/build/v1alpha1/build.go
- pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build.go
- pkg/reconciler/build/build.go
* template CRDs are include in this change so their metadata.generation
increments
* the build controller now uses the /status endpoint on update
```release-note
Build CRDs now have the status subresource enabled
```
> Enable the status subresource

- Gopkg.lock
- Gopkg.toml
- pkg/apis/build/v1alpha1/build_template_validation.go
- pkg/apis/build/v1alpha1/build_validation.go
- pkg/apis/build/v1alpha1/build_validation_test.go
- pkg/apis/build/v1alpha1/target_path_validation.go
- pkg/apis/build/v1alpha1/target_path_validation_test.go
- third_party/VENDOR-LICENSE
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
- vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
- vendor/github.com/knative/pkg/apis/field_error.go
- vendor/github.com/knative/pkg/controller/controller.go
- vendor/github.com/knative/pkg/controller/stats_reporter.go
- vendor/github.com/knative/pkg/test/spoof/spoof.go
- vendor/github.com/knative/pkg/test/zipkin/util.go
- vendor/github.com/knative/pkg/webhook/webhook.go
This pr _attempts_ to fix #484
*if a user tries to create a `Build` with a `BuildSpec` that has both `Template` and `Steps` return `ErrDisallowedFields(b.spec.steps)` because a `BuildTemplate` already includes `Steps` for the `Build` through its `BuildTemplateSpec`:
https://github.com/knative/build/blob/47e45d6af31266829e0eb362f0f250e70e041a63/pkg/apis/build/v1alpha1/build_template_types.go#L69
> fix (build_validation) Incorrect field paths returned

- hack/release.sh
Fixes #468 
* Renames `release.yaml` to `build.yaml`
```release-note
Renamed release.yaml to build.yaml
```
> Align release filename with serving repo.

- pkg/reconciler/build/apply.go
- pkg/reconciler/build/apply_test.go
now parameterized:
- `$.spec.volumes[]name`
- `$.spec.volumes[]persistentVolumeClaim.claimName`
```yaml
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
spec:
parameters:
- name: VOLUME_MOUNT
description: Name of volume to mount in the build pod.
default: cache
- name: BUILD_CACHE
description: Name of PersistentVolumeClaim to use as a cache for this build.
steps: []
volumes:
- name: ${VOLUME_MOUNT} # now parameterized
persistentVolumeClaim:
claimName: ${BUILD_CACHE} # now parameterized
```
```release-note
BuildTemplates can now have parameterized volume name and persistent
volume claimName.
```
> Allow PersistentVolumeClaims to be parameterized

- pkg/credentials/dockercreds/creds.go
- pkg/credentials/dockercreds/creds_test.go
- Merge knative flavored `kubernetes.io/basic-auth` creds with
`kubernetes.io/dockerconfigjson` ones
- knative flavored creds takes precedences over the `dockerconfigjson` one's
Fixes #389 
/cc @ImJasonH @mattmoor @AkihiroSuda
PS: porting this to `knative/build-pipeline` too :angel: 
> creds-init: add support for kubernetes.io/dockerconfigjson

- pkg/credentials/dockercreds/creds.go
- pkg/credentials/dockercreds/creds_test.go
Adding support for `kubernetes.io/dockercfg` in addition to knative's
flavored credentials and `kubernetes.io/dockerconfigjson`.
If all three of them are used (aka attach to the serviceAccount used
for the TaskRun or PipelineRun), `creds-init` will attempt to merge
entries from both of them. Knative flavored creds takes precedence
over the `dockerconfigjson`, which takes precendence over `dockercfg`
in case of duplicate entries.
This is linked to the work happening in https://github.com/knative/build-pipeline/pull/394 and a follow-up of #536.
/cc @ImJasonH @shashwathi 
> creds-init: add support for `kubernetes.io/dockercfg` too

- pkg/reconciler/build/apply.go
- pkg/reconciler/build/apply_test.go
- test/e2e/simple_test.go
* This change allows to use templating for volumes of type Secret 
```release-note
BuildTemplate now supports the replacement of secret names with parameters
```
> Allow templating for Volumes of type secret

- Gopkg.lock
- hack/release.sh
- test/e2e-tests-yaml.sh
- test/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
#458 updated test-infra without updating the release script, thus it's broken.
Addresses https://github.com/knative/test-infra/issues/387
Bonuses:
* update test-infra, so markdown link checker doesn't fail for local references
* remove unnecessary code from e2e test scripts.
> Fix release script

- pkg/reconciler/build/build.go
- pkg/reconciler/build/resources/pod.go
- pkg/reconciler/build/resources/pod_test.go
- pkg/reconciler/build/validation_test.go
- test/e2e/simple_test.go
Fixes #542 
Dummy pod name from #519 makes API response unreliable:  
https://github.com/knative/build/issues/542#issuecomment-459802297
`MakePod` function uses `build.Status.Cluster.PodName` to create new pod instead of generating new unique name
```release-note
NONE
```
> Don't generate dummy pod name

- .ko.yaml.release
Related to #566 (not sure if it's the full fix)
This seems to be related to the broken release because the prow job that autoreleased `release-0.4` branch logged this line:
```
I0220 16:35:17.750] 2019/02/20 16:35:17 error processing import paths in "config/999-cache.yaml": UNKNOWN: Project 'projects/knative-release' not found or deleted.
```
> Fix typo in .ko.yaml.release

- Gopkg.lock
- test/e2e-tests.sh
- vendor/github.com/knative/test-infra/scripts/library.sh
- vendor/github.com/knative/test-infra/scripts/release.sh
* Update to latest test-infra commit 
* Use test-infra's generalized `dump_app_logs` function and remove Build's implementation
> Update test-infra, use its function for pod logs

- config/controller.yaml
- config/webhook.yaml
This is the "build" version of https://github.com/knative/serving/pull/3332
We're seeing OOM issues at the Node level when we don't set the limit.
This will allow the pod to restart gracefully w/o taking down the entire node.
I'm not stuck on the specific value so we can pick a different one.
Signed-off-by: Doug Davis <dug@us.ibm.com>
```release-note
NONE
```
/lint
> Set memory limits

- README.md
This change only affects to the readme file. It will not change anything on the binary.
Knative build documentation and Overview documentation links are broken. They must contain `docs` folder.
> Fix broken build and overview documentation links.

- pkg/reconciler/build/resources/pod.go
This allows usrs to specify custom labels.
> Propagate the labels form the build on the pod

- cmd/git-init/main.go
- test/e2e/e2e.go
- test/git-source/1-commitid.yaml
Copying solution from tektoncd pipeline: https://github.com/tektoncd/pipeline/pull/555
Credit to @dibbles on the original PR
Fixes https://github.com/knative/build/issues/212
```release-note
Include support for git source with commit ID for revision
```
> Add support for git commit sha

- pkg/logs/logs.go
Previously builds used to hang for failed builds with any non "buildExecuteFailed" reasons.
For more details: Fixes #579 
* Exit for any build failures
> Exit tailing logs for failed builds

- DEVELOPMENT.md
`ko` is now at https://github.com/google/ko
> point to new ko repo

- test/e2e-common.sh
Fixes https://github.com/knative/test-infra/issues/676
By default, `kubectl delete` estimates a timeout if not provided, which makes the deletion not always guaranteed. Add timeout explicitly to avoid later failures
> Add timeout to kubectl delete to avoid later failures

- OWNERS
- OWNERS_ALIASES
Keep the repo reviewers as they were before (as /hack and /test are fine).
Part of knative/test-infra#579
> Remove unnecessary build-reviewers

- Gopkg.lock
- Gopkg.toml
- hack/update-deps.sh
- vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/breaking-change.md
- vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/bug-fix.md
- vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/normal-change.md
- vendor/github.com/knative/pkg/.github/pull-request-template.md
- vendor/github.com/knative/pkg/Gopkg.lock
- vendor/github.com/knative/pkg/apis/duck/typed.go
- vendor/github.com/knative/pkg/hack/update-deps.sh
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/batchv1/job/fake/fake.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/batchv1/job/job.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/corev1/namespace/fake/fake.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/corev1/namespace/namespace.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/corev1/serviceaccount/fake/fake.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/corev1/serviceaccount/service.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/rolebinding/fake/fake.go
- vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/rolebinding/rolebinding.go
- vendor/github.com/knative/pkg/injection/sharedmain/main.go
This form should be more hospitable to running things to auto-update `knative/pkg` and `knative/test-infra`.
I canaried this change in `knative/sample-controller`, and was able to produce: https://github.com/knative/sample-controller/pull/11
> Make a small adjustment to hack/update-deps.sh
