knative/build

pkg/controller/build/controller_test.go
Spotted while spelunking in the codebase.
=> Correct minor typo

test/e2e-tests.sh, test/e2e/README.md, test/e2e/simple_test.go
https://github.com/knative/build/pull/329
* Run both flavors of integration tests, even if either fails
* Spruce up error message
```release-note
NONE
```
/assign @shashwathi
=> Address review comments from #329

test/e2e-tests.sh
This makes the code cleaner, and allow failing faster on error.
=> Wrap YAML E2E tests in a function

.gitignore, pkg/controller/build/controller.go
Fixes #330 
* change waitForOperationAsync to waitForOperation
```release-note
NONE
```
=> Useless check err

Gopkg.lock, test/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
* Ignore not found entities when cleaning up namespace for the e2e tests
* Group test logging messages, making them consistent
* Update knative/test-infra to the latest version mostly to to
* fix the test cluster authentication when running e2e tests locally
* fix the parsing of e2e test results in same cases
Fixes https://github.com/knative/build/issues/286
=> Fixes and updates for the e2e tests

.ko.yaml, hack/release.sh, images/Dockerfile
```release-note
Cherrypicked smaller builder images changes
```
=> Release 0.1.2

cmd/controller/main.go
* Use sync wait group in build controller
=> Use errgroup

pkg/apis/build/v1alpha1/build_template_types_test.go, pkg/apis/build/v1alpha1/build_types_test.go, pkg/apis/build/v1alpha1/cluster_build_template_types_test.go, pkg/apis/build/v1alpha1/register_test.go
* Increase test coverage in build types
=> Add test for build types

OWNERS
Add shashwathi to list of Approvers in Build
From [ROLES.md](https://github.com/knative/docs/blob/1b52510c44168a99efe6179c523cd68bdac1e07b/community/ROLES.md)
Reviewer of the codebase for at least 3 months or 50% of project lifetime, whichever is shorter
Earliest Pull request submitted: 2018-07-03(yyyy-mm-dd). Finished 3 months on the projects.
Total PRs submitted:
https://github.com/knative/build/pulls?q=is%3Apr+author%3Ashashwathi
Reviewer for following PRs to the codebase
https://github.com/knative/build/pulls?q=is%3Apr+reviewed-by%3Ashashwathi
/assign @ImJasonH 
cc @dprotaso @pivotal-nader-ziada @bsnchan
=> Add shashwathi as approver

pkg/builder/nop/builder.go, pkg/builder/nop/builder_test.go, pkg/controller/build/controller.go, pkg/controller/build/controller_test.go
Fixes #265 
* Add tests for build controller
* Update error msg when cluster build template/ build template is not found 
* Add hooks in nop builder for inducing error scenarios 
/assign @ImJasonH 
/assign @pivotal-nader-ziada
=> Controller test

Gopkg.lock, Gopkg.toml, pkg/apis/build/v1alpha1/build_types_test.go, vendor/github.com/knative/pkg/apis/duck/cached.go, vendor/github.com/knative/pkg/apis/duck/enqueue.go, vendor/github.com/knative/pkg/apis/duck/interface.go, vendor/github.com/knative/pkg/apis/duck/patch.go, vendor/github.com/knative/pkg/apis/duck/proxy.go, vendor/github.com/knative/pkg/apis/duck/typed.go, vendor/github.com/knative/pkg/apis/duck/unstructured.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go, vendor/github.com/knative/pkg/apis/duck/verify.go, vendor/github.com/knative/pkg/apis/field_error.go, vendor/github.com/knative/pkg/webhook/webhook.go, vendor/k8s.io/client-go/dynamic/interface.go, vendor/k8s.io/client-go/dynamic/scheme.go, vendor/k8s.io/client-go/dynamic/simple.go
This is part kind of knative/pkg#97 as it updates knative/pkg to master and update the uses of `duck.VerifyType` (changed in knative/pkg#98)
cc @dprotaso @mattmoor
=> Bump knative/pkg to master

config/controller.yaml, config/webhook.yaml
This keeps build in sync with recent apiVersion changes in serving
=> Bump apiVersion to apps/v1 for Deployments

DEVELOPMENT.md
Instructions for a local, non-gcr.io registry.
=> DEVELOPMENT: instructions for a local registry option

pkg/controller/build/controller_test.go
Fixes #404 
Add the reactor before starting the informers, making the "write"
operation on the fake client `ReactionChain` before any "read".
Let's see if it fixes the race on the CI… couldn't reproduce on my desktop…
=> Fix TestBuildNotFoundFlow race condition

test/README.md
Fixes #405 
* illustrate how to run go tests locally
```release-note
NONE
```
=> illustrate how to run go tests locally

cmd/logs/main.go
=> Fix flag name

pkg/credentials/gitcreds/creds.go, pkg/credentials/gitcreds/creds_test.go
* Add more tests for credentials package
=> Add tests for credentials package

Gopkg.lock, test/e2e-tests.sh, test/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
Part of https://github.com/knative/test-infra/issues/186.
Bonuses:
* get latest fixes/updates for E2E test log parsing
* address knative/test-infra#170 for the build repo
=> Fix emitting E2E metrics

README.md
I'm not 100% sure of the intended meaning but I believe this gets the point across.
=> Fix confusing wording

Gopkg.lock, Gopkg.toml, pkg/reconciler/build/build.go, pkg/reconciler/buildtemplate/buildtemplate.go, pkg/reconciler/clusterbuildtemplate/clusterbuildtemplate.go, pkg/reconciler/stats.go, third_party/VENDOR-LICENSE, vendor/github.com/gobuffalo/envy/LICENSE.txt, vendor/github.com/gobuffalo/envy/envy.go, vendor/github.com/gobuffalo/envy/version.go, vendor/github.com/joho/godotenv/LICENCE, vendor/github.com/joho/godotenv/godotenv.go, vendor/github.com/knative/pkg/configmap/filter.go, vendor/github.com/knative/pkg/configmap/store.go, vendor/github.com/knative/pkg/controller/controller.go, vendor/github.com/knative/pkg/controller/stats_reporter.go, vendor/github.com/knative/pkg/test/kube_checks.go, vendor/github.com/knative/pkg/test/logging/logging.go, vendor/github.com/knative/pkg/test/spoof/spoof.go, vendor/github.com/knative/pkg/webhook/webhook.go, vendor/github.com/markbates/inflect/LICENCE, vendor/github.com/markbates/inflect/helpers.go, vendor/github.com/markbates/inflect/inflect.go, vendor/github.com/markbates/inflect/name.go, vendor/github.com/markbates/inflect/version.go
This matching where knative/serving references it (likely for the 0.2 cut).
Related to: https://github.com/knative/build/issues/393
=> Update to knative/pkg HEAD.

pkg/apis/build/v1alpha1/build_template_types.go, pkg/apis/build/v1alpha1/build_types.go, pkg/apis/build/v1alpha1/cluster_build_template_types.go
=> Drop methods no longer needed by webhook.

Gopkg.lock, hack/release.sh, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/dummy.go, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
Major changes are fixes to local repo handling and image tagging.
=> More updates to the release script

test/e2e-tests.sh
Hope this helps with debugging test failures. 
Credit to @markusthoemmes work on knative/serving [PR]( https://github.com/knative/serving/pull/2432)
=> Add bash helper function to get pod logs

cmd/creds-init/main.go
=> Fix logger name

pkg/apis/build/v1alpha1/build_validation_test.go, pkg/apis/build/v1alpha1/target_path_validation_test.go
Produced via: `github.com/client9/misspell`
=> Fix spelling errors

pkg/reconciler/build/build_test.go
This is a follow-up for #480 with more tests (from the original issue).
/cc @ImJasonH 
=> Add missing serviceaccount & secrets tests for BuildStatus validation 🚡

.github/issue-template.md, .github/pull-request-template.md, CONTRIBUTING.md, DEVELOPMENT.md, README.md, code-of-conduct.md, hack/README.md, hack/release.md, roadmap-2018.md, test/README.md, test/e2e/README.md
Produced via: `prettier --write $(find -name '*.md' | grep -v vendor)`
=> Format markdown

pkg/reconciler/build/build_test.go
This fixes a small typo that was… bother me a tiny bit :upside_down_face: 
/cc @ImJasonH @shashwathi
=> Fix a small type in `build_test.go` : createServceAccount 😅

Gopkg.lock, hack/update-deps.sh, vendor/github.com/knative/caching/Gopkg.lock, vendor/github.com/knative/caching/OWNERS, vendor/github.com/knative/caching/config/image.yaml, vendor/github.com/knative/caching/hack/OWNERS, vendor/github.com/knative/caching/hack/boilerplate/add-boilerplate.sh, vendor/github.com/knative/caching/hack/boilerplate/boilerplate.sh.txt, vendor/github.com/knative/caching/hack/update-codegen.sh, vendor/github.com/knative/caching/hack/update-deps.sh, vendor/github.com/knative/caching/hack/verify-codegen.sh, vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_types.go, vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/image_validation.go, vendor/github.com/knative/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/knative/caching/test/presubmit-tests.sh, vendor/k8s.io/code-generator/Godeps/OWNERS, vendor/k8s.io/code-generator/OWNERS, vendor/k8s.io/code-generator/cmd/client-gen/OWNERS, vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
*  Includes the latest and greatest that `knative/caching` has to offer
```release-note
NONE
```
=> bump knative/caching

pkg/reconciler/build/build.go, pkg/reconciler/build/resources/pod.go
=> update build with a dummy status first to avoid race condition of another watch event while the pod is being created

pkg/reconciler/build/resources/pod.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
=> golang format tools

Gopkg.lock, Gopkg.toml, vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go, vendor/github.com/knative/pkg/apis/duck/verify.go, vendor/github.com/knative/pkg/kmp/diff.go, vendor/github.com/knative/pkg/kmp/doc.go, vendor/github.com/knative/pkg/test/cleanup.go, vendor/github.com/knative/pkg/test/kube_checks.go, vendor/github.com/knative/pkg/test/spoof/spoof.go, vendor/github.com/knative/pkg/webhook/certs.go
Same as knative/serving as of today.
Linked to https://github.com/knative/build-pipeline/pull/432 and https://github.com/knative/build-pipeline/issues/227
/cc @bobcatfish @ImJasonH 
=> Bump knative/pkg to recent version

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json, vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
Major change: enable automatic major releases.
=> Test-Infra dependency upgrade

Gopkg.lock, pkg/apis/build/v1alpha1/build_template_validation.go, pkg/reconciler/build/apply.go, pkg/reconciler/build/resources/pod.go, pkg/reconciler/build/validate_build.go, pkg/reconciler/buildtemplate/resources/imagecache.go
For: https://github.com/knative/serving/issues/3049
* replace maps with sets
/lint
=> replace map[string]x with string set

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
=> update dep for github.com/knative/test-infra along with fixes

.ko.yaml.release, Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
Fixes #566 with #567 and also picks up #564 which is just test-infra updates.
=> Rebase release-0.4 to pick up release fix

pkg/reconciler/build/build.go
* Change the name to signify that this is not handled like a normal go error.
This is similar to https://github.com/knative/serving/pull/3950 and https://github.com/knative/eventing/pull/1104
```release-note
NONE
```
=> Change the name to signify that this is not handled like a normal go error

OWNERS, OWNERS_ALIASES, hack/OWNERS, test/OWNERS
Part of knative/test-infra#579
=> Update OWNERS to use OWNERS_ALIASES

pkg/reconciler/build/build.go, pkg/reconciler/buildtemplate/buildtemplate.go, pkg/reconciler/clusterbuildtemplate/clusterbuildtemplate.go
Supercedes #611
* After #615 the knative/pkg dep is up-to-date, and we can use the new shorthand for handling events.
cc @mattmoor
=> Use controller.HandleAll

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Produced via:
`dep ensure -update github.com/knative/test-infra`
/assign @adrcunha
=> Update github.com/knative/test-infra dependency

Gopkg.lock, vendor/github.com/knative/pkg/Gopkg.lock, vendor/github.com/knative/pkg/kmeta/names.go, vendor/github.com/knative/pkg/test/helpers/name.go, vendor/github.com/knative/pkg/test/logstream/doc.go, vendor/github.com/knative/pkg/test/logstream/interface.go, vendor/github.com/knative/pkg/test/logstream/kubelogs.go, vendor/github.com/knative/pkg/test/logstream/null.go, vendor/github.com/knative/pkg/test/request.go
Produced via:
`dep ensure -update github.com/knative/pkg`
/assign @mattmoor
=> Update github.com/knative/pkg dependency

Gopkg.lock, vendor/github.com/knative/pkg/Gopkg.lock, vendor/github.com/knative/pkg/configmap/store.go, vendor/github.com/knative/pkg/configmap/testing/configmap.go, vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/role/fake/fake.go, vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/role/role.go, vendor/github.com/knative/pkg/metrics/gcp_metadata.go, vendor/github.com/knative/pkg/test/logstream/kubelogs.go, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh
Produced via:
`dep ensure -update github.com/knative/test-infra github.com/knative/pkg`
/assign @mattmoor
=> Auto-update dependencies

Gopkg.lock, Gopkg.toml, vendor/github.com/knative/pkg/Gopkg.lock
- Prepping for 0.7 release. Update knative/pkg to latest from branch release-0.7.
```release-note
NONE
```
/cc @mattmoor
=> Updating pkg to latest for 0.7 release.

README.md
Update README.md to note that this component's deprecation has been proposed.
=> Update README to note deprecation proposal
